services:
  python:
    #image: python:3.12-slim
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:8000"  # HTTP interface
    command: uv run fastapi dev --host 0.0.0.0
    environment:
      - PYTHONUNBUFFERED=1

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=default

volumes:
  clickhouse-data:
